package exception.ex;

public class Exception1_1 {
	public static void main(String[] args) {
		
		//예외발생
//		try {
//			throw new Exception();
//		} catch (Exception e) {
//			e.printStackTrace();
//		}

		//1.NullPointException
//		String str = null;
//		
//		
//		for(int i=0; i<str.length(); i++) {
//			System.out.println(str.charAt(i));
//		}
		
		
		//2.ArrayIndexOutOfBoundsException
		int[] arr = new int[3];
		for(int i=0; i<4; i++) {
			arr[i] = i;
			System.out.println(i);
		}
		
		//
		String str ="1";
		Object obj = str;
		Integer integer = (Integer)obj;
		
		System.out.println(integer);
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
	}
}
